# -*- coding: utf-8 -*-
"""Taller2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GPvvZc9ehENpHtJMCIcr2chvoXxOirtX
"""

#Crear un bucle que cuente todos los números pares hasta el 100 ciclo for

for num in range(0,102,2):
  print(num)

#Haz una tabla de multiplicar utilizando el ciclo for ciclo for

print("TABLAS DE MULTIPLICAR")
numero = int(input("\nIngrese el numero a multiplicar "))
for num in range(13):
  print(num, " x ", numero , " = ", num * numero)

#Escribir un programa que pregunte al usuario su edad y muestre por pantalla todos los años que ha cumplido (desde 1 hasta su edad). ciclo for

edad = int(input("Digite sus edad: "))

for edad in range(0,edad,1):
  print(edad)

#Escribir un programa que pida al usuario un número entero positivo y muestre por pantalla todos los números impares desde 1 hasta ese número separados por comas.
num = int(input("Digite numero entero: "))

for num in range(1,num,2):
  print(num,",")

#Encuentra la suma de todos los números pares del 1 al 100 ciclo for

pares = 0
for i in range(0,100,2):
  # print(i)
  pares = pares + i
print(f"El total de la suma de los números pares del 0-100= {pares}")